name: Build and Release WPF App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    # Checkout du code source
    - name: Checkout repository
      uses: actions/checkout@v4.2.1
      
    # Installation de .NET
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: '8.0.x'

    # Restaurer les dépendances
    - name: Restore dependencies
      run: dotnet restore ./src/SvgToXamlTool.App

    # Compilation en mode Release
    - name: Build solution
      run: dotnet build ./src/SvgToXamlTool.App --configuration Release

    # Publier l'application WPF en Framework-dependent pour obtenir un exécutable plus léger
    - name: Publish executable
      run: dotnet publish ./src/SvgToXamlTool.App -c Release --framework net8.0-windows --self-contained false

    # Archive les fichiers publiés pour les joindre à la release
    - name: Upload artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: SvgToXamlTool
        path: ./src/SvgToXamlTool.App/bin/Release/net8.0-windows/publish/
